import os
import glob
import RNA
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

app = FastAPI()

class RNARequest(BaseModel):
    sequence: str = Field(..., example="GAGUCCUGUGAGAACUGUUGAGUAGAGUGUGAGCUCCCUG")

@app.get("/")
def health_check():
    return {"status": "ok", "service": "ViennaRNA API"}

@app.post("/analyze")
def analyze_rna(req: RNARequest):
    try:
        clean_seq = req.sequence.upper().replace('T', 'U').strip()
        
        # 1. Fold compound & MFE calculation
        fc = RNA.fold_compound(clean_seq)
        mfe_structure, mfe_energy = fc.mfe()

        # 2. Configure ViennaRNA global variable to output SVG instead of PostScript
        RNA.cvar.svg_option = 1
        
        # 3. Generate structure plot (creates a file like rna.svg or rna_ss.svg in pwd)
        RNA.file_ps_rna_plot(clean_seq, mfe_structure, "rna_plot")
        
        # Find generated SVG file (ViennaRNA appends .svg automatically)
        svg_filename = "rna_plot.svg"
        if not os.path.exists(svg_filename):
            # Fallback search if filename pattern differs
            svg_files = glob.glob("*.svg")
            if svg_files:
                svg_filename = svg_files[0]
            else:
                raise FileNotFoundError("SVG diagram file was not generated by ViennaRNA.")

        with open(svg_filename, "r", encoding="utf-8") as f:
            svg_content = f.read()

        # Clean up generated file
        if os.path.exists(svg_filename):
            os.remove(svg_filename)

        return {
            "sequence": clean_seq,
            "mfe_structure": mfe_structure,
            "mfe_energy_kcal": round(float(mfe_energy), 2),
            "svg_xml": svg_content
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"ViennaRNA Error: {str(e)}")
